import assert from 'node:assert/strict'
import test from 'node:test'

import {
  MAX_ITEMS, addItem, classify, cleanItems, clipboardScope, dayGroup, expire, groupItems, isConcealed, removeItem, searchItems, setPinned, titleOf, whenCopied,
} from '../shared/clipboard-model.mjs'

test('a copy is a link, an email, a phone number, a number or text', () => {
  assert.equal(classify('https://osat.example/notes?id=4'), 'link')
  assert.equal(classify('  http://localhost:5173  '), 'link')
  assert.equal(classify('see https://osat.example for more'), 'text')
  assert.equal(classify('jordan@example.com'), 'email')
  assert.equal(classify('jordan at example'), 'text')
  assert.equal(classify('(555) 010-2299'), 'phone')
  assert.equal(classify('+1 555 010 2299'), 'phone')
  assert.equal(classify('5550102299'), 'phone')
  assert.equal(classify('1234567'), 'number')
  assert.equal(classify('$1,299.50'), 'number')
  assert.equal(classify('42'), 'number')
  assert.equal(classify('-3.5%'), 'number')
  assert.equal(classify('Call Jordan 555'), 'text')
})

test('what password managers and the Mac mark as concealed is never kept', () => {
  assert.equal(isConcealed(['text/plain', 'org.nspasteboard.ConcealedType']), true)
  assert.equal(isConcealed(['text/plain', 'org.nspasteboard.TransientType']), true)
  assert.equal(isConcealed(['text/plain', 'org.nspasteboard.AutoGeneratedType']), true)
  assert.equal(isConcealed(['text/plain', 'com.agilebits.onepassword']), true)
  assert.equal(isConcealed(['public.utf8-plain-text', 'org.keepassxc.KeePassXC.password']), true)
  assert.equal(isConcealed(['text/plain', 'text/html']), false)
  assert.equal(isConcealed([]), false)
})

const text = (value) => ({ kind: classify(value), text: value })
let count = 0
const id = () => `c-${++count}`

test('a new copy goes on top; the same copy moves up instead of repeating', () => {
  let items = []
  for (const value of ['one', 'two', 'three']) items = addItem(items, text(value), { id: id(), now: new Date(`2026-09-29T10:0${items.length}:00Z`) }).items
  assert.deepEqual(items.map((item) => item.text), ['three', 'two', 'one'])
  const again = addItem(items, text('one'), { id: id(), now: new Date('2026-09-29T11:00:00Z') })
  assert.deepEqual(again.items.map((item) => item.text), ['one', 'three', 'two'])
  assert.equal(again.added.id, items[2].id, 'the same copy keeps its id')
  assert.equal(again.added.at, '2026-09-29T11:00:00.000Z')
  assert.equal(again.items.length, 3)
})

test('the list is capped and says what fell off, so the picture files can go', () => {
  let items = []
  let dropped = []
  for (let n = 0; n < MAX_ITEMS + 3; n += 1) ({ items, dropped } = addItem(items, text(`copy ${n}`), { id: id() }))
  assert.equal(items.length, MAX_ITEMS)
  assert.equal(items[0].text, `copy ${MAX_ITEMS + 2}`)
  assert.equal(dropped.length, 1)
  assert.equal(dropped[0].text, 'copy 2')
})

test('pictures are deduped by their hash and stay under a total size', () => {
  const picture = (key, bytes) => ({ kind: 'image', key, image: { w: 10, h: 10, bytes }, thumb: 'data:image/png;base64,AA' })
  let result = addItem([], picture('a', 60), { id: 'i-a', maxImages: 100 })
  result = addItem(result.items, picture('a', 60), { id: 'i-x', maxImages: 100 })
  assert.equal(result.items.length, 1)
  assert.equal(result.items[0].id, 'i-a')
  result = addItem(result.items, picture('b', 60), { id: 'i-b', maxImages: 100 })
  assert.deepEqual(result.items.map((item) => item.id), ['i-b'], 'the older picture made room')
  assert.deepEqual(result.dropped.map((item) => item.id), ['i-a'])
  const mixed = addItem(result.items, text('words'), { id: 'i-t', maxImages: 100 })
  assert.deepEqual(mixed.items.map((item) => item.id), ['i-t', 'i-b'])
})

test('Today, Yesterday and Earlier, by the calendar; empty groups are left out', () => {
  const now = new Date(2026, 8, 29, 9, 30)
  const at = (day, hour) => new Date(2026, 8, day, hour).toISOString()
  assert.equal(dayGroup(at(29, 0), now), 'Today')
  assert.equal(dayGroup(at(28, 23), now), 'Yesterday')
  assert.equal(dayGroup(at(27, 12), now), 'Earlier')
  const items = [{ id: 'a', at: at(29, 8) }, { id: 'b', at: at(28, 8) }, { id: 'c', at: at(20, 8) }, { id: 'd', at: at(29, 7) }]
  assert.deepEqual(groupItems(items, now).map((group) => [group.label, group.items.map((item) => item.id)]), [['Today', ['a', 'd']], ['Yesterday', ['b']], ['Earlier', ['c']]])
  assert.deepEqual(groupItems([items[0]], now).map((group) => group.label), ['Today'])
})

test('search finds words in a copy, or a kind of copy', () => {
  const items = [
    { id: '1', kind: 'text', text: 'Invoice for Jordan, due Friday' },
    { id: '2', kind: 'link', text: 'https://osat.example/pricing' },
    { id: '3', kind: 'image', hash: 'h', image: { bytes: 5 } },
  ]
  assert.deepEqual(searchItems(items, 'jordan friday').map((item) => item.id), ['1'])
  assert.deepEqual(searchItems(items, 'link').map((item) => item.id), ['2'])
  assert.deepEqual(searchItems(items, 'image').map((item) => item.id), ['3'])
  assert.deepEqual(searchItems(items, '').map((item) => item.id), ['1', '2', '3'])
  assert.deepEqual(searchItems(items, 'nothing'), [])
})

test('"v" alone, or "v" and words, is the clipboard; other words that start with v are not', () => {
  assert.deepEqual(clipboardScope('v'), { query: '' })
  assert.deepEqual(clipboardScope('V'), { query: '' })
  assert.deepEqual(clipboardScope('v invoice'), { query: 'invoice' })
  assert.equal(clipboardScope('very good'), null)
  assert.equal(clipboardScope('ve'), null)
  assert.equal(clipboardScope(''), null)
})

test('a copy is shown in one short line, and said when', () => {
  assert.equal(titleOf({ kind: 'text', text: '\n  First line here \nsecond' }), 'First line here')
  assert.equal(titleOf({ kind: 'link', text: 'https://www.example.com/a/b' }), 'example.com/a/b')
  assert.equal(titleOf({ kind: 'link', text: 'https://example.com/' }), 'example.com')
  assert.equal(titleOf({ kind: 'image' }), 'Image')
  const now = new Date(2026, 8, 29, 15, 0)
  assert.equal(whenCopied(new Date(2026, 8, 29, 14, 59, 40).toISOString(), now), 'just now')
  assert.equal(whenCopied(new Date(2026, 8, 29, 14, 56).toISOString(), now), '4 minutes ago')
  assert.equal(whenCopied(new Date(2026, 8, 29, 12, 0).toISOString(), now), '3 hours ago')
  assert.match(whenCopied(new Date(2026, 8, 28, 16, 30).toISOString(), now), /^Yesterday, 4:30\sPM$/)
  assert.match(whenCopied(new Date(2026, 8, 20, 9, 5).toISOString(), now), /^Sep 20, 9:05\sAM$/)
})

test('a saved file is read back with only what OSAT writes, and nothing broken', () => {
  const good = { id: 'a', kind: 'text', at: '2026-09-29T10:00:00Z', text: 'hello' }
  const picture = { id: 'p', kind: 'image', at: '2026-09-29T10:00:00Z', hash: 'h', image: { w: 4, h: 3, bytes: 99 }, thumb: 'data:x' }
  const items = cleanItems([good, { ...good, secret: 'x' }, { id: 'b', kind: 'text', at: 'nope', text: 'x' }, { id: 'c', kind: 'weird', at: good.at, text: 'x' }, { id: 'd', kind: 'text', at: good.at, text: '' }, picture, null, 4])
  assert.deepEqual(items, [good, picture])
  assert.deepEqual(cleanItems('nope'), [])
  assert.deepEqual(removeItem(items, 'a').map((item) => item.id), ['p'])
})

test('a pinned copy is never dropped by the count, the age or a repeat', () => {
  let items = []
  items = addItem(items, text('snippet'), { id: 'p', now: new Date('2026-08-01T10:00:00Z'), max: 2 }).items
  items = setPinned(items, 'p', true)
  for (const value of ['a', 'b', 'c']) items = addItem(items, text(value), { id: id(), now: new Date('2026-09-28T10:00:00Z'), max: 2 }).items
  assert.deepEqual(items.map((item) => item.text), ['c', 'b', 'snippet'])
  const again = addItem(items, { ...text('snippet'), app: 'Notes' }, { id: id(), now: new Date('2026-09-29T10:00:00Z'), max: 2 })
  assert.equal(again.added.pinned, true, 'a repeat keeps its pin')
  assert.equal(again.added.app, 'Notes')
  const aged = expire(again.items, { now: new Date('2026-09-29T12:00:00Z'), days: 7 })
  assert.deepEqual(aged.items.map((item) => item.text), ['snippet', 'c', 'b'])
  const old = expire([{ id: 'x', at: '2026-01-01T00:00:00Z' }, { id: 'y', at: '2026-01-01T00:00:00Z', pinned: true }], { now: new Date('2026-09-29T00:00:00Z'), days: 30 })
  assert.deepEqual(old.items.map((item) => item.id), ['y'])
  assert.deepEqual(old.dropped.map((item) => item.id), ['x'])
  assert.deepEqual(expire([{ id: 'x', at: '2000-01-01T00:00:00Z' }], { days: 0 }).items.length, 1, '0 days means no age limit')
  assert.equal(setPinned(items, 'p', false).find((item) => item.id === 'p').pinned, undefined)
})

test('pins come first in the groups, and a search can be narrowed to text, links or pictures', () => {
  const now = new Date(2026, 8, 29, 9, 30)
  const at = new Date(2026, 8, 29, 8).toISOString()
  const items = [
    { id: '1', kind: 'text', at, text: 'Invoice for Jordan', app: 'Mail' },
    { id: '2', kind: 'link', at, text: 'https://osat.example', pinned: true },
    { id: '3', kind: 'image', at, hash: 'h', image: { bytes: 5 } },
    { id: '4', kind: 'email', at, text: 'jordan@example.com' },
  ]
  assert.deepEqual(groupItems(items, now).map((group) => [group.label, group.items.map((item) => item.id)]), [['Pinned', ['2']], ['Today', ['1', '3', '4']]])
  assert.deepEqual(searchItems(items, '', { kind: 'text' }).map((item) => item.id), ['1', '4'])
  assert.deepEqual(searchItems(items, '', { kind: 'link' }).map((item) => item.id), ['2'])
  assert.deepEqual(searchItems(items, '', { kind: 'image' }).map((item) => item.id), ['3'])
  assert.deepEqual(searchItems(items, 'mail').map((item) => item.id), ['1', '4'], 'the app it came from can be searched too')
  assert.deepEqual(clipboardScope('clip invoice', 'clip'), { query: 'invoice' })
  assert.equal(clipboardScope('v', ''), null, 'no keyword, no scope')
})

test('a saved list keeps only what fits the limit and never a pin', () => {
  const list = ['a', 'b', 'c', 'd'].map((name) => ({ id: name, kind: 'text', at: '2026-09-29T10:00:00Z', text: name, ...(name === 'd' ? { pinned: true } : {}) }))
  assert.deepEqual(cleanItems(list, { max: 2 }).map((item) => item.id), ['a', 'b', 'd'])
})
