/* The clipboard history's pure pieces (Phase 13): what a copy is, what is never kept, how the
   list stays short (and young) and free of repeats, and how it is grouped, searched and described.
   Main (desktop/launcher/clipboard-history.cjs) and the windows use the same rules.
   Nothing here touches the clipboard or the disk, and nothing logs what was copied. */

export const MAX_ITEMS = 200
export const MAX_DAYS = 30
export const MAX_TEXT = 50000
// A picture is kept as a file only while it is small; the pictures together stay under a cap too.
export const MAX_IMAGE_BYTES = 6 * 1024 * 1024
export const MAX_IMAGES_TOTAL = 150 * 1024 * 1024
// What the window is sent of a long copy; the whole copy still goes back on the clipboard.
export const PREVIEW_CHARS = 6000
// What Settings → Launcher offers for "how much to keep": how many copies, and for how many days (0: no age limit).
export const ITEM_CHOICES = [50, 100, 200, 500]
export const DAY_CHOICES = [7, 30, 90, 0]
// A copied picture's row shows a small thumbnail that fits a THUMB × THUMB square (a tall screenshot stays small too);
// it is kept in history.json, so one that is somehow bigger is dropped rather than saved.
export const THUMB = 96
export const MAX_THUMB_CHARS = 60000

export function thumbSize(width, height, max = THUMB) {
  const w = Math.max(1, Number(width) || 1)
  const h = Math.max(1, Number(height) || 1)
  const scale = Math.min(1, max / Math.max(w, h))
  return { width: Math.max(1, Math.round(w * scale)), height: Math.max(1, Math.round(h * scale)) }
}

/* A copied text dragged into another app goes as a small .txt file named after its first words. */
export function dragName(text) {
  const first = String(text || '').split('\n').map((line) => line.trim()).find(Boolean) || ''
  const name = first.replace(/[/\\:*?"<>|\u0000-\u001f]/g, ' ').replace(/^[.\s]+/, '').replace(/\s+/g, ' ').slice(0, 40).trim()
  return `${name || 'Copied text'}.txt`
}

/* Password managers and the Mac mark a copy they don't want kept (nspasteboard.org): concealed,
   transient (a one-time code) or generated on the spot. OSAT never keeps these. */
export const CONCEALED_TYPES = [
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
  'com.agilebits.onepassword',
  'com.1password.1password',
  'de.petermaurer.TransientPasteboardType',
  'com.typeit4me.clipping',
  'Pasteboard generator type',
  'net.antelle.keeweb',
]
const MANAGER_WORDS = /onepassword|1password|keepass|bitwarden|lastpass|dashlane|keychain|enpass|nordpass|proton\.?pass/i

/* `formats` is every type on the clipboard right now. */
export function isConcealed(formats = []) {
  return formats.some((format) => CONCEALED_TYPES.includes(format) || MANAGER_WORDS.test(format))
}

/* What a copied text is: a link, an email address, a phone number, a number, or plain text. */
export function classify(text) {
  const value = String(text ?? '').trim()
  if (/^https?:\/\/[^\s]+$/i.test(value)) return 'link'
  if (/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(value)) return 'email'
  const digits = value.replace(/\D/g, '')
  if (/^\+?[\d\s().-]+$/.test(value) && digits.length >= 7 && digits.length <= 15 && (/[\s().+-]/.test(value) || digits.length >= 10)) return 'phone'
  if (/^[-+]?[$€£]?\s?\d[\d,]*(\.\d+)?\s?%?$/.test(value)) return 'number'
  return 'text'
}

export const KIND_LABEL = { text: 'Text', link: 'Link', email: 'Email address', phone: 'Phone number', number: 'Number', image: 'Image' }

/* The three filters the quick search offers: words, links, pictures. */
export const KIND_FILTERS = [['all', 'All'], ['text', 'Text'], ['link', 'Links'], ['image', 'Images']]
const inFilter = (item, filter) => (filter === 'all' || !filter ? true : filter === 'text' ? item.kind !== 'link' && item.kind !== 'image' : item.kind === filter)

/* One line to show for a copy in a list. */
export function titleOf(item) {
  if (item.kind === 'image') return 'Image'
  const text = String(item.text || '')
  if (item.kind === 'link') {
    try {
      const url = new URL(text.trim())
      return `${url.host.replace(/^www\./, '')}${url.pathname === '/' ? '' : url.pathname}`.slice(0, 90)
    } catch { /* shown as text */ }
  }
  return (text.split('\n').map((line) => line.trim()).find(Boolean) || text.trim() || 'Empty').slice(0, 90)
}

/* A new copy, as { kind, text?, image?, thumb?, key, app? } → the list, newest first, no repeats
   (the same copy moves to the top and keeps its pin), no more than `max` unpinned copies (and no
   more picture bytes than `maxImages`); a pinned copy is never dropped. Answers { items, added,
   dropped }: `dropped` are the copies that fell off, so their picture files can go too. `key` is
   what makes two copies the same (the text, or the picture's hash). */
export function addItem(items, incoming, { id, now = new Date(), max = MAX_ITEMS, maxImages = MAX_IMAGES_TOTAL } = {}) {
  const keyOf = (item) => (item.kind === 'image' ? `image:${item.hash}` : `text:${item.text}`)
  const same = items.find((item) => keyOf(item) === (incoming.kind === 'image' ? `image:${incoming.key}` : `text:${incoming.text}`))
  const at = now.toISOString()
  const app = typeof incoming.app === 'string' && incoming.app ? incoming.app.slice(0, 60) : undefined
  const added = same
    ? { ...same, at, ...(app ? { app } : {}) }
    : incoming.kind === 'image'
      ? { id, kind: 'image', at, hash: incoming.key, image: incoming.image, thumb: incoming.thumb, ...(app ? { app } : {}) }
      : { id, kind: incoming.kind, at, text: incoming.text, ...(incoming.more ? { more: true } : {}), ...(app ? { app } : {}) }
  const dropped = []
  let unpinned = 0
  let bytes = 0
  const list = [added, ...items.filter((item) => item !== same)].filter((item) => {
    if (item.kind === 'image') bytes += item.image?.bytes || 0
    if (item.pinned) return true
    if (++unpinned > max || (item.kind === 'image' && bytes > maxImages)) { dropped.push(item); return false }
    return true
  })
  return { items: list, added, dropped }
}

/* Copies older than `days` days go (0 or none: no age limit); pinned ones stay. */
export function expire(items, { now = new Date(), days = MAX_DAYS } = {}) {
  if (!days) return { items, dropped: [] }
  const cutoff = now.getTime() - days * 86400000
  const dropped = items.filter((item) => !item.pinned && Date.parse(item.at) < cutoff)
  return dropped.length ? { items: items.filter((item) => !dropped.includes(item)), dropped } : { items, dropped }
}

export const removeItem = (items, id) => items.filter((item) => item.id !== id)

/* Pin or unpin: a pin is a snippet, kept whatever the limits say. */
export const setPinned = (items, id, on) => items.map((item) => {
  if (item.id !== id) return item
  const { pinned, ...rest } = item
  return on ? { ...rest, pinned: true } : rest
})

/* What a saved file may hold: only the fields OSAT writes, nothing else. */
export function cleanItems(value, { max = MAX_ITEMS } = {}) {
  if (!Array.isArray(value)) return []
  const seen = new Set()
  const items = []
  for (const item of value) {
    if (!item || typeof item.id !== 'string' || seen.has(item.id) || Number.isNaN(Date.parse(item.at))) continue
    seen.add(item.id)
    const extra = { ...(item.pinned === true ? { pinned: true } : {}), ...(typeof item.app === 'string' && item.app ? { app: item.app.slice(0, 60) } : {}) }
    if (item.kind === 'image') {
      if (typeof item.hash === 'string' && Number.isFinite(item.image?.bytes)) items.push({ id: item.id, kind: 'image', at: item.at, hash: item.hash, image: { w: Number(item.image.w) || 0, h: Number(item.image.h) || 0, bytes: item.image.bytes }, thumb: typeof item.thumb === 'string' && item.thumb.length <= MAX_THUMB_CHARS ? item.thumb : '', ...extra })
    } else if (typeof item.text === 'string' && item.text && item.kind in KIND_LABEL && item.kind !== 'image') {
      items.push({ id: item.id, kind: item.kind, at: item.at, text: item.text.slice(0, MAX_TEXT), ...(item.more ? { more: true } : {}), ...extra })
    }
  }
  // The newest copies stay when the limit shrank; pins always stay.
  let unpinned = 0
  return items.filter((item) => item.pinned || ++unpinned <= max)
}

const dayKey = (date) => `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`

/* Today, Yesterday or Earlier, by the Mac's own calendar. */
export function dayGroup(at, now = new Date()) {
  const when = new Date(at)
  const yesterday = new Date(now)
  yesterday.setDate(now.getDate() - 1)
  if (dayKey(when) === dayKey(now)) return 'Today'
  if (dayKey(when) === dayKey(yesterday)) return 'Yesterday'
  return 'Earlier'
}

/* [{ label, items }], pins first ("Pinned"), then Today, Yesterday and Earlier; empty groups left out. */
export function groupItems(items, now = new Date()) {
  const loose = items.filter((item) => !item.pinned)
  return [
    { label: 'Pinned', items: items.filter((item) => item.pinned) },
    ...['Today', 'Yesterday', 'Earlier'].map((label) => ({ label, items: loose.filter((item) => dayGroup(item.at, now) === label) })),
  ].filter((group) => group.items.length)
}

/* Words find text; "image", "link", "email", "phone" or "number" find that kind; `kind` ('text',
   'link', 'image') narrows to one of the quick search's filters. */
export function searchItems(items, query, { kind = 'all' } = {}) {
  const words = String(query || '').toLowerCase().split(/\s+/).filter(Boolean)
  const of = items.filter((item) => inFilter(item, kind))
  if (!words.length) return of
  return of.filter((item) => {
    const hay = `${item.text || ''}\n${KIND_LABEL[item.kind]}\n${item.app || ''}`.toLowerCase()
    return words.every((word) => hay.includes(word))
  })
}

/* "v" alone, or "v" and words, means the clipboard: → { query } or null. `keyword` is the one
   typed to mean it (Settings → Launcher can change it). */
export function clipboardScope(text, keyword = 'v') {
  const word = String(keyword || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '')
  if (!word) return null
  const match = new RegExp(`^${word}(?:\\s+([\\s\\S]*))?$`, 'i').exec(String(text || '').trim())
  return match ? { query: (match[1] || '').trim() } : null
}

const CLOCK = new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' })
const DAY = new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' })

/* "just now", "4 minutes ago", "2 hours ago", "Yesterday, 4:30 PM", "Sep 27". */
export function whenCopied(at, now = new Date()) {
  const when = new Date(at)
  const minutes = Math.round((now - when) / 60000)
  if (minutes < 1) return 'just now'
  if (minutes < 60) return `${minutes} ${minutes === 1 ? 'minute' : 'minutes'} ago`
  const group = dayGroup(at, now)
  if (group === 'Today') { const hours = Math.floor(minutes / 60); return `${hours} ${hours === 1 ? 'hour' : 'hours'} ago` }
  if (group === 'Yesterday') return `Yesterday, ${CLOCK.format(when)}`
  return `${DAY.format(when)}, ${CLOCK.format(when)}`
}
